commerce_static_bundle.static_bundle_type.*:
  type: config_entity
  label: 'Static bundle type config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    uuid:
      type: string
