commerce_product_bundle.commerce_product_bundle_type.*:
  type: config_entity
  label: 'Product bundle type'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    description:
      type: text
      label: 'Description'
    bundleItemType:
      type: string
      label: 'Bundle item type'
    orderItemType:
      type: string
      label: 'Order item type'
